language: cpp
dist: focal

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libsfml-dev cmake libopencv-dev wget unzip

script:
    ############################################################################
    # Download and extract pytorch
    ############################################################################
     - wget https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.7.1%2Bcpu.zip
     - unzip -q libtorch-cxx11-abi-shared-with-deps-1.7.1+cpu.zip

    ############################################################################
    # Build main and tests
    ############################################################################
     - mkdir -p build
     - cd build
     - cmake ..
     - make
     - make test
